[package]
name = "custom_server_module"
version = "0.1.0"
edition = "2021"

[dependencies]
spacetimedb = "1.1.0"
log = "0.4"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
stdb_shared = { path = "../SharedModule" } 