[target.x86_64-pc-windows-msvc]
linker = "link.exe"
rustflags = [
    "-C", "target-feature=-crt-static",
    "-C", "link-arg=/DEFAULTLIB:msvcrt.lib",
    "-C", "link-arg=/DEFAULTLIB:msvcprt.lib",
    "-C", "link-arg=/DEFAULTLIB:oldnames.lib",
    "-C", "link-arg=/LIBPATH:C:\\Program Files\\Microsoft Visual Studio\\2022\\Enterprise\\VC\\Tools\\MSVC\\14.38.33130\\lib\\x64",
    "-C", "link-arg=/LIBPATH:C:\\Program Files (x86)\\Windows Kits\\10\\Lib\\10.0.22621.0\\um\\x64",
    "-C", "link-arg=/LIBPATH:C:\\Program Files (x86)\\Windows Kits\\10\\Lib\\10.0.22621.0\\ucrt\\x64",
]

[build]
target = "x86_64-pc-windows-msvc"
